### PR TITLE
Extend feature set for ATEM 8K

### PR DESCRIPTION
**Pull request by cxselph**
Everything seems to work like it should in the companion admin. I am still waiting on one to do testing with the actual switcher. Let me know if there are any changes or suggestions. I have seen that some people are starting to receive theirs and are itching to try it out with this glorious software.

Features added:
Additional inputs
Additional auxes
Additional dsks
Additional presets
Additional multi viewers/windows
Additional supersource

Thanks

### CODE REVIEW

**Comment by krocheck** [comment]
I'm reviewing this.  May tweak a couple things.

**Comment by krocheck** [comment]
@cxselph did you test the multi-view routing?  My first read suggests this would need an update in the upstream atem-connection library.

**Comment by krocheck** [comment]
Another question is going to be how we will handle the switcher when its in 8K mode.  Most are going to run it in UHD/HD, so this is a moot issue for the time being but it will need to be addressed.

**Comment by cxselph** [comment]
@krocheck I haven't tested multiview routing. I am hoping to get my hands on the switcher by the end of this week or early next. I agree, there will probably need to be a decent upgrade to the ATEM connection for all the features to work, especially the handling changing between 8K and the HD/UHD modes. Would it make sense to rename model 9 with HD/UHD and add a model 10 with 8K and the limited number of features just in case someone needs 8K? If the main features work well, it could be usable with a manual choice in the instance setup until things can be updated with a compatible atem-connection library for proper auto detection.

**Comment by krocheck** [comment]
@cxselph the model id actually is reported by the unit, so we need to see the behavior between the two modes.  Number 9 is a guess right now as its the next unused value.  I'll have to check if resolution reporting is available in atem-connection.  BMD has been pretty good about keeping the protocol forward/backward compatible ... but when new features are dropped in it gets tricky because it all needs to be reverse engineered.

**Comment by cxselph** [comment]
@krocheck I have been testing everything this morning with the switcher and so far it seems to be  functioning as expected. There is still time for something to pop up. :) 
DSKs 1-4 - Tested OK (Toggle/On/Off), Changing key/fill sources.
Inputs 1-40 - Tested OK (Setting inputs to PVW/PGM, sources for MV)
MV Routing - Tested OK - Will need to add notes to the help file. All windows are numbered based on total of 16 windows per MV. If you turn a block of 4 into 1 window, its number is based on the upper left window in the smaller quad. ie: 1, 3, 9, 11.
SS2 - Tested OK

Auxes(Outputs) - Tested OK

The error below is the complaint about using autodetect to choose the right module since the atem-connection still needs to be updated for this model.
24. 11:38:54 instance(atem 8k): Connected to a , but instance is configured for 4 ME Constellation 8K. Change instance to 'Auto Detect' or the appropriate model to ensure stability.

I will continue testing. Let me know if there is anything you would like me to try.

**Comment by krocheck** [comment]
What happens if let it auto-detect the model?

**Comment by cxselph** [comment]
It detects it as Model 0. All of the variable populated ok. You just loose all extra inputs and outputs, etc.
I did get my first issue. It lost connection and showed the following in instance config.

IMG_1957

**Comment by krocheck** [comment]
Since we're in limbo for v1.4.0 and I don't want to pull this into core until we get some questions answered; I'm going to close this PR out and have you submit a new PR to a branch: https://github.com/bitfocus/companion-module-atem/tree/feature-8k-constellation

That way we can work on it together easier.

**Pull request closed without merging**
