### PR TITLE
Typescript and refactoring

### PR DESCRIPTION
**Pull request by Julusian**
This is a refactor of the module to be written in typescript. This brings some better type safety within the module and should make it easier to make small changes with certainty of not breaking anything, and ensure nothing is missed.

As an example, one advantage here is that the feedback and actions systems use enums now. If someone tries to use a feedback id that is not in that enum the compiler will complain. This is also true if it is not included in the handlers, as there is a check to ensure all values are handled in the switch cases.

It is a bit of a hack as companion core doesnt have typescript definitions, so it doesnt play nicely, but I shall try and get them to support typescript in modules to make this cleaner and easier. 

As part of this, I have gone through and tested every action, feedback and preset against my 2ME running 8.0.1, and everything is working nicely. Additionally, I tested most of it against a constellation running in both HD and 8K modes.

Other improvements:
* Better handling of unknown models. Try and parse out the various fields from the state.
* Remove the internal state tracking, and use the state object created by atem-connection directly.
* Improve source/macro names in the dropdowns. Use the names from the device if possible.
* Use less hardcoded arrays of options when possible
* Split code into shorter files, to make it easier to browse and find bits

Left to do:
- [x] Remaining Constellation support #21
- [x] Update atem-connection to release version
- [x] Update readme for new workflow
- [x] Dont commit dist folder
- [x] Verify the postinstall script works for ci builds etc
- [x] #15 
- [x] #18
- [x] #19
- [x] #23
- [x] #24
- [x] #25

### CODE REVIEW

**Comment by krocheck** [comment]
@Julusian where are you at with this ... besides the obvious from the checklist above?  I'll give this a merge on your go.

**Comment by cxselph** [comment]
@Julusian Just poking around and testing with your update and noticed that the available USK's show up as 1-16 on each me instead of ME1 1-4, etc... for actions and same with presets at least with the constellation. I am not getting errors. I know you still have things to work on. Just thought I would let you know. Thanks for all the hard work.

{
    id: Enums.Model.Constellation,
    label: 'Constellation',
    inputs: 40,
    auxes: 24,
    MEs: 4,
    **USKs: 16, Should be 4**
    DSKs: 4,
    MPs: 4,
    MVs: 4,
    multiviewerFullGrid: true,
    SSrc: 2,
    macros: 100
  },

**Comment by Julusian** [comment]
@krocheck That todo list is accurate on what I have left to do. Ill try and finish it up today, then I'll let you know once it is good.

@cxselph Good spot, that should be resolved now.

**Comment by Julusian** [comment]
@krocheck I am happy that this is working and done now.

If you are happy I can merge it and raise a pr to get the module updated in core.

**Pull request merged**
