### PR TITLE
Create custom feedbacks on single button using up to 4 sources to program

### PR DESCRIPTION
**Pull request by cxselph**
This fixes https://github.com/bitfocus/companion-module-atem/issues/9
Everything is working well in my tests. The new options based on how many M/Es you have.

### CODE REVIEW

**Comment by krocheck** [comment]
I would highly recommend you implement the same for preview before we proceed.  Otherwise this looks good (pending validation).

**Comment by krocheck** [comment]
Question, though.  Instead of implementing as you have, which is elegant given its dropdown friendly nature, might it be better with a single 'Change colors from multiple program sources' feedback?  The input in that case would be a textbox with a regex validated string in the form:

`ME#=SRC#,ME#=SRC#,...`

Yes, its more complex because the user needs to know the numbers instead of picking from a dropdown.  In contrast however, we wouldn't be bloating the interface (especially for the 4 M/Es) with a ton more feedback types.  Plus it easy to change from 2 to 3 source checks instead of having to remove and add a different feedback.

Just some food for thought.

**Comment by cxselph** [comment]
Sounds good. I will get the preview side added and then work on the dropdowns to make it more fancy. Thanks

**Comment by cxselph** [comment]
I have added preview functionality now. I will consider this phase one. I will have to work on Keith's suggestion to combine these into one feedback option in the future when I get more time to figure out how I would try to do it. Let me know if you need any changes.

**Comment by cxselph** [comment]
@krocheck Can you have a look at my latest? I will need lots more time to try and figure out the combining the 3 new feedback options for PGM/PVW. At my JS skill level, it may take some time. I can put this feature to use immediately and save lots of time. Also, with the whole idea of making things simple for users, I think it would be best that we didn't require users to type in ME's and Sources manually into a REGEX field. It would require an input list be available every time setup was needed. In my environment where volunteers get involved, they may not have access to that info without giving them access to too much. Thoughts? Questions? Let me know. Thanks

**Comment by krocheck** [comment]
I've been going back and forth on this for the same reason you note in terms of usability.  I think its fine.

I'm going to pull it into my dev/test environment later today to validate what you've done.  Been noodling on other things, so I haven't had a chance to do that yet.

**Comment by cxselph** [comment]
Thanks

**Pull request merged**
